### ISSUE TITLE
Forestry Textures not loading in 1.11.2/1.12

### ISSUE THREAD

**Issue by LukewarmYeti** [CyanideX/Unity#129]
Unsure why, but Unity's Forestry textures don't load for me in both 1.11.2 and 1.12. Maybe due to forestry updating how they load their textures which is causing conflict with resource packs? They have been updating the mod a whole lot since their first 1.10.2 release.

Saw you guys are planning on making Gendustry textures, that still on hold? I understand people are extremely busy. Also, anything you can tease about future updates to this mod? I've been following it for a little while now, love to know about some upcoming stuff.

Cheers.

Edit: It looks like some textures i.e. backpacks are using Unity's textures, but I haven't had an extensive look. Many (probably >75% at a glance) textures are not using Unity's though. I have checked in comparison to the 1.10.2 version which seems to work fine.

**Comment by Yulife** [comment]
Can you check again? I fixed this iirc

**Comment by LukewarmYeti** [comment]
Checked again as requested.

1.12, latest forestry (beta) + Unity 1.5.0. - Pretty sure is the same for 1.11. 

Still the same for me. Some of the textures load, e.g. capsules, scoop, backpacks etc.

Some examples of the ones not loading inc: All electron tubes; circuit boards; iodine capsule; pickaxe & shovel kit; both pickaxe & shovel; All the gears; apiarists armor, all electron tubes, all bee combs, etc. 

I've crossed checked within the Unity zip file to make sure those textures are included. (couldn't find electron tubes but I am sure they were in 1.10).

Pictures to help: http://imgur.com/a/YRrHL < first picture shows that gears/electron tubes/tools - thinking about it most of the top row doesn't have unity textures - etc.

Second & Third pics show backpacks + capsules do have unity textures, (e.g. compare capsules to the iodine capsules which doesn't have a Unity texture).

**Comment by Yulife** [comment]
Did you DL the latest from Github

**Comment by LukewarmYeti** [comment]
Ahh I can see your commits on the 1.12_plus branch and haven't tested that version. However I'm not extremely familiar with GitHub and I am unsure whether I just click download or require extra software to access/create the fully created resource pack.

Edit: Figured it out, yes looks fixed to me, the textures are there! There are no textures for circuit boards but I think they weren't part of forestry in 1.7.10 and therefore weren't implemented into Unity.
